### ISSUE TITLE
싱글페이지 라우팅 Research

### ISSUE THREAD

**Issue by hustle-dev** [sosoYim/POT#26]
- [ ] 라우팅 공부

공부 후에 여기에 멘션 달아주세요!

**Comment by sonwonjae** [comment]
라우팅 공부 후 우리의 웹앱을 기준으로 라우팅 테스트해보면 좋을 것 같습니다.

**Comment by sonwonjae** [comment]
저희는 pjax방식으로 진행할 것입니다
